name: Build WebRTC APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17  # 升级到 17, 满足 sdkmanager 要求
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses && yes | sdkmanager --update  # 强制接受

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-v4-${{ hashFiles('**/*.gradle*') }}  # 更新 key 清缓存
          restore-keys: |
            ${{ runner.os }}-gradle-v4-

      - name: Grant permission to gradlew
        run: chmod +x gradlew

      - name: Clean build
        run: ./gradlew clean  # 清理 stale outputs

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace --no-daemon --refresh-dependencies --rerun-tasks

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: webrtc-1080p-apk
          path: app/build/outputs/apk/debug/app-debug.apk
