name: Build 1080p WebRTC APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 关键修复：JDK 11 → JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'          # 改成 17！
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant permission
        run: chmod +x ./gradlew

896      - name: Clean
        run: ./gradlew clean --no-daemon

      - name: Build APK
        run: ./gradlew assembleDebug --no-daemon --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: webrtc-1080p.apk
          path: app/build/outputs/apk/debug/app-debug.apk
